version: '3.3'
services:
    vpn:
        image: ritazh/l2tpvpn  
        restart: always
        ports:
                - 500:500/udp
                - 4500:4500/udp
        environment:
            MYIP: 192.168.0.101
            MYGATEWAY: 192.168.0.1
            MYUSERNAME: vpn
            MYPASSWORD: vpn
            MYSECRET: vpn
          
        privileged: true
        network_mode: "host"
        volumes:
            - "/lib/modules:/lib/modules:ro"
